In [335]:
import numpy as np
from numpy import dot
from numpy.linalg import norm
import pandas as pd
import os
import sys
np.random.seed(42)

tests = {
    'index_nonzero':[(np.random.choice(range(0, 3), n),) for n in range(1, 11)],
    'change_array':[(np.random.choice(range(0, 10), n), 0) for n in range(1, 11)],
    'closest_value':[(np.random.choice(range(-10, 10), n), 1.33) for n in range(1, 11)],
    'first_odds':[(x,) for x in range(1, 11)],
    'diag_prod':[(np.random.choice(range(-10, 10), size=(x, x)),) for x in range(2, 12)],
    'antiderivative':[(np.random.choice(range(0, 10), n),) for n in range(1, 11)],
    'make_symmetric':[(np.triu(np.random.choice(range(-10, 10), size=(x, x))),) for x in range(2, 12)],
    'construct_matrix':[(*np.random.choice(range(1, 5), 2), 7) for _ in range(1, 11)],
    'cosine_similarity':[(np.random.normal(size=n), np.random.normal(size=n)) for n in range(2, 12)],
}

df_tests = pd.DataFrame(data=tests)

obj = np.load('test.npz', mmap_mode='r')

result = pd.DataFrame([])
cnt = -1

for func in tests.keys():
    for i in range(len(tests[func])):
        cnt += 1
        test = tests[func][i]
        try:
            student_answer = getattr(sys.modules[__name__], func)(*test)
            right_answer = obj['arr_{}'.format(cnt)]
            if func == 'cosine_similarity':
                student_answer = round(float(student_answer), 4)
                right_answer = round(float(right_answer), 4)
            check = student_answer == right_answer
            if func == 'antiderivative':
                check = check[:-1]
            if type(check) == bool:
                if check:
                    result.at[i, func] = 'OK'
                    continue
            else:
                if (check).all():
                    result.at[i, func] = 'OK'
                    continue
        except Exception as err:
            result.at[i, func] = 'ER'
            print('Не пройден тест ')
            print(func, *test)
            print('Ошибка во время исполнения: ', type(err), err)
            continue
        
        print('Не пройден тест {}'.format(cnt + 1))
        print(func, *test)
        print('Твой ответ: ')
        print(student_answer)
        print('Должен быть: ')
        print(right_answer)
        result.at[i, func] = 'WA'

In [336]:
print('''Я, Печерицына Мария, выполнила работу самостоятельно и без использования операторов while,
      for, if. Ноутбук прилагаю. Получил следующие результаты:''')
result

Я, Печерицына Мария, выполнила работу самостоятельно и без использования операторов while,
      for, if. Ноутбук прилагаю. Получил следующие результаты:


index_nonzero change_array closest_value first_odds diag_prod  \
0            OK           OK            OK         OK        OK   
1            OK           OK            OK         OK        OK   
2            OK           OK            OK         OK        OK   
3            OK           OK            OK         OK        OK   
4            OK           OK            OK         OK        OK   
5            OK           OK            OK         OK        OK   
6            OK           OK            OK         OK        OK   
7            OK           OK            OK         OK        OK   
8            OK           OK            OK         OK        OK   
9            OK           OK            OK         OK        OK   

  antiderivative make_symmetric construct_matrix cosine_similarity  
0             OK             OK               OK                OK  
1             OK             OK               OK                OK  
2             OK             OK               OK                OK  
3             OK             OK               OK                OK  
4             OK             OK               OK                OK  
5             OK             OK               OK                OK  
6             OK             OK               OK                OK  
7             OK             OK               OK                OK  
8             OK             OK               OK                OK  
9             OK             OK               OK                OK

Во всех задачах необходимо написать код решения внутри функции и проверить его работу, вызвав функцию для данных из условия.

При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if` (даже внутри генераторов).

Везде, где встречаются массивы или матрицы, подразумевается, что это `numpy.array`. 

### 1

Напишите функцию, которая возвращает индексы ненулевых элементов. Например, если на вход поступает массив `array([1, 2, 0, 0, 4, 0])`, то на выходе должен получиться массив `array([0, 1, 4])`.

_Функции, которые могут пригодиться при решении: `.where()`, `.nonzero()`_

In [53]:
def index_nonzero(a):
    return a.nonzero()[0]

In [23]:
#Проверьте корректность работы функции

In [54]:
a = np.array([1, 2, 0, 0, 4, 0])

In [55]:
index_nonzero(a)

array([0, 1, 4])

### 2

Напишите функцию, меняющую все четные значения массива целых чисел на заданное число. Например, если на вход поступает массив `array([3, 5, 1, 0, -3, 22, 213436])` и число `-111`, то на выходе должен получиться массив `array([   3,    5,    1, -111,   -3, -111, -111])`.

In [277]:
def change_array(array, number):
    return np.where(array % 2 == 0, number, array)
    #ваш код здесь 

In [6]:
#Проверьте корректность работы функции

In [283]:
a = np.array([3, 5, 1, 0, -3, 22, 213436])

In [282]:
n = -111

In [284]:
change_array(a, n)

array([   3,    5,    1, -111,   -3, -111, -111])

### 3

Напишите функцию, вычисляющую самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. В случае неоднозначного ответа должно выводиться число с наименьшим индексом.

_Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_

In [308]:
def closest_value(array, value):
    min = np.abs(array - value).argmin()
    max = np.abs(array - value).argmax()
    return (array[min], array[max])
    #ваш код здесь

In [8]:
#Проверьте корректность работы функции

In [312]:
a = np.array([0, 1, 2, 3, 4])

In [311]:
v = 1.33

In [313]:
closest_value(a, v)

(1, 4)

### 4

Напишите функцию, создающую массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`.

*Функции, которые могут пригодиться при решении: `.arange()`*

In [119]:
def first_odds(n):
    return np.flip(np.arange(1,  2*n, 2))
    #ваш код здесь

In [10]:
#Проверьте корректность работы функции

In [131]:
n = 5

In [132]:
first_odds(n)

array([9, 7, 5, 3, 1])

### 5

Напишите функцию, вычисляющую произведение всех ненулевых диагональных элементов на диагонали данной квадратной матрицы. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{pmatrix},
$$
то ответом будет 32.

_Функции, которые могут пригодиться при решении: `.diagonal()`, `.prod()`_

In [158]:
def diag_prod(matrix):
    diag = np.diagonal(matrix)
    return np.prod(diag[diag != 0])
    #ваш код здесь

In [154]:
#Проверьте корректность работы функции

In [163]:
matrix = np.matrix([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [164]:
diag_prod(matrix)

32

### 6

Напишите функцию, вычисляющую какую-нибудь первообразную данного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$.

_Функции, которые могут пригодиться при решении: `.append()`_

In [170]:
def antiderivative(coefs):
    return np.polyint(coefs)
    #ваш код здесь

In [14]:
#Проверьте корректность работы функции

In [166]:
a = np.array([4, 6, 0, 1])

In [171]:
antiderivative(a)

array([1., 2., 0., 1., 0.])

### 7

Напишите функцию, делающую данную [треугольную матрицу](https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B5%D1%83%D0%B3%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0) симметричной. Например, если на вход поступает матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
0 & 5 & 6 & 7\\
0 & 0 & 8 & 9\\
0 & 0 & 0 & 10\\
\end{pmatrix},
$$
то на выходе должна быть матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
2 & 5 & 6 & 7\\
3 & 6 & 8 & 9\\
4 & 7 & 9 & 10\\
\end{pmatrix}.
$$

_Функции, которые могут пригодиться при решении: `.diag()`, `.diagonal()`, `.T`_

In [318]:
def make_symmetric(matrix):
    return matrix + matrix.T - np.diag(np.diag(matrix))
    #ваш код здесь

In [16]:
#Проверьте корректность работы функции

In [319]:
m = np.matrix([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])

In [320]:
make_symmetric(m)

matrix([[ 1,  2,  3,  4],
        [ 2,  5,  6,  7],
        [ 3,  6,  8,  9],
        [ 4,  7,  9, 10]])

### 8

Напишите функцию, создающую прямоугольную матрицу из m одинаковых строк, заполненных последовательными натуральными числами от a до b включительно в возрастающем порядке. Например, если m = 5, a = 3, b = 10, то на выходе будет матрица
$$
\begin{pmatrix}
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
\end{pmatrix}
$$

_Функции, которые могут пригодиться при решении: `.arange()`, `.zeros()`, а также [broadcasting rules](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)._

In [203]:
def construct_matrix(m, a, b):
    zero_mat = np.zeros((m, b-a+1), int)
    line = np.arange(a, b+1)
    return np.asmatrix(zero_mat+line)
    #ваш код здесь

In [18]:
#Проверьте корректность работы функции

In [195]:
m = 5

In [196]:
a = 3

In [197]:
b = 10

In [204]:
construct_matrix(m, a, b)

matrix([[ 3,  4,  5,  6,  7,  8,  9, 10],
        [ 3,  4,  5,  6,  7,  8,  9, 10],
        [ 3,  4,  5,  6,  7,  8,  9, 10],
        [ 3,  4,  5,  6,  7,  8,  9, 10],
        [ 3,  4,  5,  6,  7,  8,  9, 10]])

### 9

Напишите функцию, вычисляющую [косинусную близость](https://en.wikipedia.org/wiki/Cosine_similarity) двух векторов. Например, если на вход поступают вектора `array([-2, 1, 0, -5, 4, 3, -3])` и `array([0, 2, -2, 10, 6, 0, 0])`, ответом будет -0.25.

_Функции, которые могут пригодиться при решении: `.dot()`, `.norm()`, `.sum()`_

In [331]:
def cosine_similarity(vec1, vec2):
    return dot(vec1, vec2)/(norm(vec1)*norm(vec2))
    #ваш код здесь

In [20]:
#Проверьте корректность работы функции

In [332]:
vec1 = np.array([-2, 1, 0, -5, 4, 3, -3])

In [333]:
vec2 = np.array([0, 2, -2, 10, 6, 0, 0])

In [334]:
cosine_similarity(vec1, vec2)

-0.25